name: come_n_fix
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  cloud_firestore: ^4.17.3
  custom_rating_bar: ^3.0.0
  file_picker: ^8.0.5
  firebase_auth: ^4.19.5
  firebase_core: ^2.31.0
  firebase_storage: ^11.7.6
  flutter:
    sdk: flutter
  geocoding: ^3.0.0
  geoflutterfire2: ^2.3.15
  geolocator: ^12.0.0
  google_maps_flutter: ^2.6.1
  image: ^4.2.0
  image_picker: ^1.1.1
  loading_animation_widget:
  path: ^1.9.0
  table_calendar: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  # flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
