// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC90OoGiMYqzPVrFhwNeHRzykDGhcjU7yI',
    appId: '1:313694454053:web:c26bb569b89f93d3231acc',
    messagingSenderId: '313694454053',
    projectId: 'comenfix-8f86a',
    authDomain: 'comenfix-8f86a.firebaseapp.com',
    storageBucket: 'comenfix-8f86a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAosEobHF3Zp2fs-FXI5f8Q-Psz5jVGmcg',
    appId: '1:313694454053:android:454d2c9d6f87d624231acc',
    messagingSenderId: '313694454053',
    projectId: 'comenfix-8f86a',
    storageBucket: 'comenfix-8f86a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDC8Tg0-AIvg3ZW-aR5tP-kDDOLBzjKjVg',
    appId: '1:313694454053:ios:f99d5aefd5734391231acc',
    messagingSenderId: '313694454053',
    projectId: 'comenfix-8f86a',
    storageBucket: 'comenfix-8f86a.appspot.com',
    iosBundleId: 'com.example.comeNFix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDC8Tg0-AIvg3ZW-aR5tP-kDDOLBzjKjVg',
    appId: '1:313694454053:ios:f99d5aefd5734391231acc',
    messagingSenderId: '313694454053',
    projectId: 'comenfix-8f86a',
    storageBucket: 'comenfix-8f86a.appspot.com',
    iosBundleId: 'com.example.comeNFix',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC90OoGiMYqzPVrFhwNeHRzykDGhcjU7yI',
    appId: '1:313694454053:web:2523d2168ca12f89231acc',
    messagingSenderId: '313694454053',
    projectId: 'comenfix-8f86a',
    authDomain: 'comenfix-8f86a.firebaseapp.com',
    storageBucket: 'comenfix-8f86a.appspot.com',
  );
}
